USE ecommerce_jogos;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE Cartao;
TRUNCATE TABLE Cliente;
TRUNCATE TABLE Endereco;
TRUNCATE TABLE EntradaEstoque;
TRUNCATE TABLE ItemPedido;
TRUNCATE TABLE LogTransacoes;
TRUNCATE TABLE Pedido;
TRUNCATE TABLE Produto;
TRUNCATE TABLE ProdutoCategoria;
TRUNCATE TABLE Telefone;
SET FOREIGN_KEY_CHECKS = 1;