USE ecommerce_jogos;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Cartao;
TRUNCATE TABLE Cliente;
TRUNCATE TABLE Endereco;
TRUNCATE TABLE Telefone;

TRUNCATE TABLE EntradaEstoque;
TRUNCATE TABLE Produto;
TRUNCATE TABLE ProdutoCategoria;

TRUNCATE TABLE ItemPedido;
TRUNCATE TABLE Pedido;
TRUNCATE TABLE Troca;
TRUNCATE TABLE ItemTroca;
TRUNCATE TABLE Cupom;

TRUNCATE TABLE PagamentoPedido;
TRUNCATE TABLE Notificacao;

TRUNCATE TABLE LogTransacoes;

SET FOREIGN_KEY_CHECKS = 1;